# Generated by Django 5.1.1 on 2025-09-12 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('deadline', models.DateTimeField(verbose_name='期限')),
                ('assignee', models.CharField(max_length=100, verbose_name='担当者')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '仕掛中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='進捗')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'ordering': ['-created_at'],
            },
        ),
    ]
