# Generated by Django 5.1.1 on 2025-09-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', '仕事'), ('personal', '個人'), ('study', '学習'), ('health', '健康'), ('finance', '財務'), ('other', 'その他')], default='work', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
    ]
